from django.db import models

class Name(models.Model):
    objects = models.Manager()
    tei_id = models.CharField(max_length=50, unique=True)
    surname = models.CharField(max_length=100)
    forename = models.CharField(max_length=100)
    alt_names = models.CharField(max_length=100) 
    birth = models.CharField(max_length=20)
    death = models.CharField(max_length=20)
    viaf = models.CharField(max_length=100)
    odnb = models.CharField(max_length=100)
    seg = models.TextField(max_length=1000) 
    footnote = models.CharField(max_length=5000)
    notes = models.TextField(max_length=5000)
    class Meta:
        db_table = 'names'

class Document(models.Model):
    objects = models.Manager()
    tei_id = models.CharField(max_length=200, unique=True)
    eliot_vol = models.CharField(max_length=200)
    eliot_part = models.CharField(max_length=200)
    eliot_period = models.CharField(max_length=200)
    eliot_toc = models.CharField(max_length=200)
    src_title_a = models.CharField(max_length=200)
    src_title_m = models.CharField(max_length=200)
    src_title_j = models.CharField(max_length=200)
    src_date = models.CharField(max_length=200)
    src_pub = models.CharField(max_length=200)
    src_plc = models.CharField(max_length=200)
    src_vol = models.CharField(max_length=200)
    src_pg = models.CharField(max_length=200)
    src_id = models.CharField(max_length=200)
    alt1_title_a = models.CharField(max_length=200)
    alt1_title_m = models.CharField(max_length=200)
    alt1_title_j = models.CharField(max_length=200)
    alt1_date = models.CharField(max_length=200)
    alt1_pub = models.CharField(max_length=200)
    alt1_plc = models.CharField(max_length=200)
    alt1_vol = models.CharField(max_length=200)
    alt1_pg = models.CharField(max_length=200)
    alt1_id = models.CharField(max_length=200)
    alt2_title_a = models.CharField(max_length=200)
    alt2_title_m = models.CharField(max_length=200)
    alt2_title_j = models.CharField(max_length=200)
    alt2_date = models.CharField(max_length=200)
    alt2_pub = models.CharField(max_length=200)
    alt2_plc = models.CharField(max_length=200)
    alt2_vol = models.CharField(max_length=200)
    alt2_pg = models.CharField(max_length=200)
    alt2_id = models.CharField(max_length=200)
    alt3_title_a = models.CharField(max_length=200)
    alt3_title_m = models.CharField(max_length=200)
    alt3_title_j = models.CharField(max_length=200)
    alt3_date = models.CharField(max_length=200)
    alt3_pub = models.CharField(max_length=200)
    alt3_plc = models.CharField(max_length=200)
    alt3_vol = models.CharField(max_length=200)
    alt3_pg = models.CharField(max_length=200)
    alt3_id = models.CharField(max_length=200)
    notes = models.TextField(max_length=5000)
    class Meta:
        db_table = 'documents'

class Mention(models.Model):
    name = models.ForeignKey(Name)
    document = models.ForeignKey(Document)
    type = models.CharField(max_length=20)
    class Meta:
        db_table = 'mentions'
